version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      # - DATABASE_URL=postgresql://postgres:gettingstarted@localhost:5432/tododb
      -DATABASE_URL=postgresql://todo_db_5z68_user:5Ib7ULP3seiKsCguiTyrtLmv7AdPyfoB@dpg-cugt1jbtq21c73f3kg00-a.oregon-postgres.render.com/todo_db_5z68
      - PORT=5001

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gettingstarted
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
