version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:gettingstarted@localhost:5432/tododb
      - PORT=5000

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gettingstarted
      - POSTGRES_DB=tododb
    ports:
      - "5432:5432"
